CREATE TABLE login_history (
	IDX INT NOT NULL,
	userid VARCHAR(70),
	retry INT,
	lastFailedLogin BIGINT,
	lastSuccessedLogin BIGINT,
	clientIp VARCHAR(15),
	PRIMARY KEY (IDX)
) ENGINE=MyISAM;

CREATE TABLE board_comment (
	IDX INT NOT NULL,
	WRITER VARCHAR(50) NOT NULL,
	CONTENT VARCHAR(500) NOT NULL,
	WRITEDATE DATE NOT NULL,
	LINKEDARTICLENUM INT NOT NULL,
	WRITERID VARCHAR(50) NOT NULL,
	PRIMARY KEY (IDX)
) ENGINE=MyISAM;


CREATE TABLE board_member (
	IDX INT NOT NULL,
	USERID VARCHAR(70) NOT NULL,
	USERPW VARCHAR(50) NOT NULL,
	USERNAME VARCHAR(50) NOT NULL,
	PINNO VARCHAR(15),
	JOINDATE DATE,
	PRIMARY KEY (IDX)
) ENGINE=MyISAM;

insert into board_member(idx,userid,userpw,username) values(1,'admin','openeg','admin');



CREATE TABLE openeg_security (
	userid VARCHAR(70) NOT NULL,
	salt VARCHAR(70),
	seckey VARCHAR(120),
	PRIMARY KEY (userid)
) ENGINE=MyISAM;



CREATE TABLE board (
	IDX INT NOT NULL,
	WRITER VARCHAR(50) NOT NULL,
	SUBJECT VARCHAR(150) NOT NULL,
	content VARCHAR(6000),
	HITCOUNT INT NOT NULL,
	RECOMMENDCOUNT INT NOT NULL,
	WRITEDATE DATE NOT NULL,
	WRITERID VARCHAR(50) NOT NULL,
	FILENAME VARCHAR(100),
	SAVEDFILENAME VARCHAR(100),
	PRIMARY KEY (IDX)
) ENGINE=MyISAM;



